//
// AddressModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class AddressModel: JSONModel {

    var id: Int?
    var firstName: String?
    var lastName: String?
    var address1: String?
    var address2: String?
    var city: String?
    var state: String?
    var zip: String?
    var phone: String?
    var status: Int?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["firstName"] = self.firstName
        nillableDictionary["lastName"] = self.lastName
        nillableDictionary["address1"] = self.address1
        nillableDictionary["address2"] = self.address2
        nillableDictionary["city"] = self.city
        nillableDictionary["state"] = self.state
        nillableDictionary["zip"] = self.zip
        nillableDictionary["phone"] = self.phone
        nillableDictionary["status"] = self.status
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
