//
// CheckoutModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class CheckoutModel: JSONEncodable {

    var offerId: Int?
    var ordersPendingId: Int?
    var userId: Int?
    var billingAddressId: Int?
    var shipZipCode: Int?
    var creditCardId: Int?
    var shipAddressId: Int?
    var bottlesQty: Int?
    var useCredit: Bool?
    var promoCode: String?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["offerId"] = self.offerId
        nillableDictionary["ordersPendingId"] = self.ordersPendingId
        nillableDictionary["userId"] = self.userId
        nillableDictionary["billingAddressId"] = self.billingAddressId
        nillableDictionary["shipZipCode"] = self.shipZipCode
        nillableDictionary["creditCardId"] = self.creditCardId
        nillableDictionary["shipAddressId"] = self.shipAddressId
        nillableDictionary["bottlesQty"] = self.bottlesQty
        nillableDictionary["useCredit"] = self.useCredit
        nillableDictionary["promoCode"] = self.promoCode
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
