//
// OfferDetailItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class OfferDetailItem: JSONEncodable {

    var wineryNotes: String?
    var wineryAbout: String?
    var metaDescription: String?
    var metaKeywords: String?
    var metaTitle: String?
    var wines: [WineDetailitem]?
    var liveFeed: [LiveFeedItem]?
    var title: String?
    var wineryName: String?
    var offerImageUrl: String?
    var pricePerBottle: Int?
    var bottlesRemaining: Int?
    var featureStatus: Int?
    var minPrice: Double?
    var maxPrice: Double?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["wineryNotes"] = self.wineryNotes
        nillableDictionary["wineryAbout"] = self.wineryAbout
        nillableDictionary["metaDescription"] = self.metaDescription
        nillableDictionary["metaKeywords"] = self.metaKeywords
        nillableDictionary["metaTitle"] = self.metaTitle
        nillableDictionary["wines"] = self.wines?.encode()
        nillableDictionary["liveFeed"] = self.liveFeed?.encode()
        nillableDictionary["title"] = self.title
        nillableDictionary["wineryName"] = self.wineryName
        nillableDictionary["offerImageUrl"] = self.offerImageUrl
        nillableDictionary["pricePerBottle"] = self.pricePerBottle
        nillableDictionary["bottlesRemaining"] = self.bottlesRemaining
        nillableDictionary["featureStatus"] = self.featureStatus
        nillableDictionary["minPrice"] = self.minPrice
        nillableDictionary["maxPrice"] = self.maxPrice
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
