//
// OfferItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class OfferItem: JSONEncodable {

    var title: String?
    var wineryName: String?
    var offerImageUrl: String?
    var pricePerBottle: Int?
    var bottlesRemaining: Int?
    var featureStatus: Int?
    var minPrice: Double?
    var maxPrice: Double?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["title"] = self.title
        nillableDictionary["wineryName"] = self.wineryName
        nillableDictionary["offerImageUrl"] = self.offerImageUrl
        nillableDictionary["pricePerBottle"] = self.pricePerBottle
        nillableDictionary["bottlesRemaining"] = self.bottlesRemaining
        nillableDictionary["featureStatus"] = self.featureStatus
        nillableDictionary["minPrice"] = self.minPrice
        nillableDictionary["maxPrice"] = self.maxPrice
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
