//
// PaymentModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class PaymentModel: JSONEncodable {

    var cardNumber: String?
    var authNetUserProfileId: String?
    var authNetPaymentProfileId: String?
    var billingAddressId: Int?
    var cvv: String?
    var firstName: String?
    var lastName: String?
    var expiryYear: String?
    var expiryMonth: String?
    var id: Int?
    var cardType: String?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["cardNumber"] = self.cardNumber
        nillableDictionary["authNetUserProfileId"] = self.authNetUserProfileId
        nillableDictionary["authNetPaymentProfileId"] = self.authNetPaymentProfileId
        nillableDictionary["billingAddressId"] = self.billingAddressId
        nillableDictionary["cvv"] = self.cvv
        nillableDictionary["firstName"] = self.firstName
        nillableDictionary["lastName"] = self.lastName
        nillableDictionary["expiryYear"] = self.expiryYear
        nillableDictionary["expiryMonth"] = self.expiryMonth
        nillableDictionary["id"] = self.id
        nillableDictionary["cardType"] = self.cardType
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
