//
// WineDetailitem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


class WineDetailitem: JSONEncodable {

    var name: String?
    var region: String?
    var retailPrice: Int?
    var quantity: Int?
    var winemakerNotes: String?
    var brand: String?
    var description: String?
    var tastingNotes: String?
    var varietal: String?
    var imageUrl: String?
    var wineryName: String?
    

    // MARK: JSONEncodable
    func encode() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["region"] = self.region
        nillableDictionary["retailPrice"] = self.retailPrice
        nillableDictionary["quantity"] = self.quantity
        nillableDictionary["winemakerNotes"] = self.winemakerNotes
        nillableDictionary["brand"] = self.brand
        nillableDictionary["description"] = self.description
        nillableDictionary["tastingNotes"] = self.tastingNotes
        nillableDictionary["varietal"] = self.varietal
        nillableDictionary["imageUrl"] = self.imageUrl
        nillableDictionary["wineryName"] = self.wineryName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
